[[plugins]]
package = "@netlify/plugin-sitemap"

[[edge_functions]]
path = "/geolocation"
function = "geolocation"

[[edge_functions]]
path = "/index"
function = "index"

[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"