[[plugins]]
  package = "@netlify/plugin-sitemap"

[context.production.environment]
  BASE_PATH = "/academy"


# [[redirects]]
#   from = "/test"
#   to = "/game"
#   status = 301
#   force = true


# [[redirects]]
#   from = "/:locale/blog/category/:splat/page/:page"
#   to = "/:locale/blog/category/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "/static"
#   to = "/static"
#   status = 200
#   force = true


# [[redirects]]
#   from = "/10/*"
#   to = "/123/:splat"
#   status = 301
#   force = true

[[redirects]]
  from = "/:locale/blog/:splat"
  to = "/blog/:locale/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/:locale/blog"
  to = "/blog/:locale"
  status = 200
  force = true

# [[redirects]]
#   from = "/:locale/blog/*"
#   to = "/:locale/:splat"
#   status = 200
#   force = true


# [[redirects]]
#   from = "/academy/*"
#   to = "/:splat"
#   status = 200
#   force = true


# [[redirects]]
#   from = "/:locale/blog"
#   to = "/blog/:locale"
#   status = 200
#   force = true

