[[plugins]]
package = "@netlify/plugin-sitemap"

[[edge_functions]]
path = "/geolocation"
function = "geolocation"

[[edge_functions]]
path = "/serverside"
function = "serverside"

[build.environment]
#NEXT_USE_NETLIFY_EDGE = "true"
NEXT_PUBLIC_TEST = "NEXT_PUBLIC_TEST"