[[plugins]]
package = "@netlify/plugin-sitemap"

[[edge_functions]]
path = "/geolocation"
function = "geolocation"

[[edge_functions]]
path = "/serverside"
function = "serverside"

[build.environment]
#NEXT_USE_NETLIFY_EDGE = "true"
NEXT_PUBLIC_TEST = "NEXT_PUBLIC_TEST"

[functions]
  included_files = ["!node_modules/geoip-lite/data/geoip-city.dat"]