[[plugins]]
  package = "@netlify/plugin-sitemap"

# [[edge_functions]]
#   path = "/blog/*"
#   function = "rewrite"

# [[edge_functions]]
#   path = "/*"
#   function = "rewrite"


# [[redirects]]
#   from = "/test"
#   to = "/game"
#   status = 301
#   force = true


# [[redirects]]
#   from = "/:locale/blog/category/:splat/page/:page"
#   to = "/:locale/blog/category/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "/static"
#   to = "/static"
#   status = 200
#   force = true


# [[redirects]]
#   from = "/10/*"
#   to = "/123/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "/:locale/blog/:splat"
#   to = "/blog/:locale/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = "/blog/*"
  to = "/:splat"
  status = 301
  force = true

# [[redirects]]
#   from = "/:locale/blog/*"
#   to = "/:locale/:splat"
#   status = 200
#   force = true


[[redirects]]
  from = "/academy/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image"
  query = {w = ":width", q = ":quality", url = ":url"}
  to = "/_ipx/w_:width,q_:quality/https://i.ytimg.com/vi/UKl7R5bpVeQ/sddefault.jpg"
  status = 200
  force = true



# [[redirects]]
#   from = "/:locale/blog"
#   to = "/blog/:locale"
#   status = 200
#   force = true

# The URL for each edge function
# [[edge_functions]]
#   function = "transform"
#   path = "/*"
  

  [[headers]]
  for = "/ru/coin-price-chart"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/es/coin-price-chart"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/pt/coin-price-chart"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/ru/coin-price-chart/:splat"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/es/coin-price-chart/:splat"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/serverside"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/1"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
