
[[redirects]]
  from = "/test"
  to = "/game"
  status = 301
  force = true

# [[redirects]]
#   from = "/static"
#   to = "/static"
#   status = 301
#   force = true

[[redirects]]
  from = "/static"
  to = "/static/:amp"
  query = {amp = ":amp"}
  status = 301
  force = true
